### ISSUE TITLE
HACS not shown in dark mode

### ISSUE THREAD

**Issue by bcutter** [frenck/home-assistant-theme-outline#12]
Outline does not apply the dark mode mods to HACS view. Neither when set to dark, nor when set to auto (and according to auto it should be dark):

![grafik](https://user-images.githubusercontent.com/13799156/120871531-25856000-c59c-11eb-9664-f402608b86f7.png)

![grafik](https://user-images.githubusercontent.com/13799156/120871231-5ca74180-c59b-11eb-8e78-8c0d24fc9030.png)

### Steps to reproduce

Open HACS control panel when Theme outline is set to dark (or auto which should be dark).

### Expected behavior

HACS background is shown in dark.

### Actual behavior

HACS background is shown in light.

**Possible starting point:**
Is HACS not supporting the new auto theme mode introduced with HA Core 2021.6 or is Outline missing something?

**Comment by frenck** [comment]
Maar that is a HACS issue. Please report it with HACS.

Thanks!

../Frenck

**Comment by bcutter** [comment]
Fixed in https://github.com/hacs/integration/issues/2099
