### ISSUE TITLE
No outline is shown on markdown cards with the 'outline ' theme selected

### ISSUE THREAD

**Issue by ManCaveMedia** [frenck/home-assistant-theme-outline#20]
# Problem/Motivation

> No outline is shown on markdown cards with the 'outline ' theme selected

## Expected behavior

> An outline on the markdown cards with the 'outline' theme selected

## Actual behavior

> No outline is shown on markdown cards with the 'outline ' theme selected. It worked before HA 2021.11.0, but not since that update.

## Steps to reproduce

> Update HA to 2021.11.0, add a markdown card, add text to it and select the 'outline' theme on the card.

## Proposed changes

> Fix the theme?

**Comment by frenck** [comment]
I don't think this is a theme issue.

**Comment by ManCaveMedia** [comment]
Yeah, sorry...
It looks like it's the same for all themes.

Will try to find where to post this bug...

**Comment by frenck** [comment]
here: https://github.com/home-assistant/frontend/issues

**Comment by ManCaveMedia** [comment]
Thanks! You're a legend.
