### ISSUE TITLE
add support for auto light/dark mode and color selections

### ISSUE THREAD

**Issue by killarny** [frenck/home-assistant-theme-outline#7]
# Problem/Motivation

> The default theme has support for automatic switching between light and dark mode, and setting accent colors. When I select the Outline theme, those options appear to be unsupported (or at least, they go away in the UI) and it would be nice if the theme supported them.

## Expected behavior

> The theme supports HA's automatic light/dark color switching and accent colors.

## Actual behavior

> Selecting the Outline theme causes the light/dark mode and accent color options to disappear.

## Steps to reproduce

> Select the default theme, observe that there are options for light/dark mode and accent colors:

![image](https://user-images.githubusercontent.com/29001/114318486-32755e00-9adb-11eb-8a33-8626c7e67edb.png)

> Select the Outline theme, observe that the options are missing:

![image](https://user-images.githubusercontent.com/29001/114318507-48831e80-9adb-11eb-8f35-d07d8c8ff538.png)

## Proposed changes

> I am new to HA, so I have no proposals for how to fix this, sorry!

**Comment by frenck** [comment]
This cannot be fixed by a theme. Home Assistant simply doesn't support that 🤷

**Comment by bcutter** [comment]
> 
> 
> This cannot be fixed by a theme. Home Assistant simply doesn't support that 🤷

So any other way to
1) preserve the automatic switch (light/dark - auto mode) of the default and
2) at the same time apply the minimal but *great* modifications Outline adds

?

Would the oldschool way "create a second outline_dark theme and add an automation which switches between light and dark theme" a way to go? That could probably only work on sun elevation, not on what default theme does (recognize clients system setting and using light/dark accordingly).

I´m really impressed how Outline improves the default light theme. But at the same time I don´t want to loose the automatic light/dark switch feature...

**Comment by frenck** [comment]
It is not possible as I already stated. Thus theme is as is.

**Comment by bcutter** [comment]
Okay, thanks for confirming. So how to change Lovelace default (and put Outline to the new default in Core)? 😁

**Comment by frenck** [comment]
Dark mode support has been added 👍

**Comment by bcutter** [comment]
Miracles happen :-) Awesome!

Looking forward to 2021.7 👍🏼

Will it support auto switch (as default) or do we need to manually switch between light/dark?

**Comment by bcutter** [comment]
Update to my last question: Hope so, at least https://www.home-assistant.io/blog/2021/06/02/release-20216/#support-for-custom-dark-mode-themes sounds very promising. Exactly what we´re looking for 👍
